# Generated by Django 5.1.15 on 2026-08-22 17:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trace',
            fields=[
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.UUIDField(default=uuid.uuid4)),
                ('user_id', models.CharField(max_length=200)),
                ('raw_prompt', models.TextField()),
                ('client_metadata', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=10)),
                ('final_decision', models.CharField(blank=True, choices=[('ALLOW', 'Allow'), ('VERIFY', 'Verify'), ('MODIFY', 'Modify'), ('HUMAN_REVIEW', 'Human Review'), ('BLOCK', 'Block')], max_length=20, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UseCaseProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_case_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('geography', models.JSONField(blank=True, default=list)),
                ('regulations', models.JSONField(blank=True, default=list)),
                ('model_tier_preference', models.CharField(choices=[('low', 'Low'), ('mid', 'Mid'), ('high', 'High'), ('expert', 'Expert')], default='mid', max_length=10)),
                ('session_risk_window', models.PositiveIntegerField(default=5)),
                ('audit_retention_days', models.PositiveIntegerField(default=90)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['use_case_id'],
            },
        ),
        migrations.CreateModel(
            name='AuditRecord',
            fields=[
                ('trace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='audit_record', serialize=False, to='core.trace')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('geography', models.JSONField(blank=True, default=list)),
                ('regulation_versions', models.JSONField(blank=True, default=dict)),
                ('pre_request', models.JSONField(blank=True, default=dict)),
                ('model_routing', models.JSONField(blank=True, default=dict)),
                ('response_metrics', models.JSONField(blank=True, default=dict)),
                ('audit_quality', models.JSONField(blank=True, default=dict)),
                ('audit_responsibility', models.JSONField(blank=True, default=dict)),
                ('composite_risk_score', models.FloatField(blank=True, null=True)),
                ('auditor_model', models.CharField(blank=True, max_length=100)),
                ('auditor_confidence', models.FloatField(blank=True, null=True)),
                ('recommended_action', models.CharField(blank=True, choices=[('ALLOW', 'Allow'), ('VERIFY', 'Verify'), ('MODIFY', 'Modify'), ('HUMAN_REVIEW', 'Human Review'), ('BLOCK', 'Block')], max_length=20, null=True)),
                ('policy_profile_version', models.CharField(blank=True, max_length=50)),
                ('policy_rules_evaluated', models.JSONField(blank=True, default=list)),
                ('policy_rules_triggered', models.JSONField(blank=True, default=list)),
                ('final_action', models.CharField(blank=True, choices=[('ALLOW', 'Allow'), ('VERIFY', 'Verify'), ('MODIFY', 'Modify'), ('HUMAN_REVIEW', 'Human Review'), ('BLOCK', 'Block')], max_length=20, null=True)),
                ('session_state_snapshot', models.JSONField(blank=True, default=dict)),
                ('modification', models.JSONField(blank=True, null=True)),
                ('human_review', models.JSONField(blank=True, null=True)),
                ('user_response', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='trace',
            name='use_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traces', to='core.usecaseprofile'),
        ),
        migrations.CreateModel(
            name='SessionState',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('turn_number', models.PositiveIntegerField(default=0)),
                ('session_risk_accumulator', models.FloatField(default=0.0)),
                ('verify_count', models.PositiveIntegerField(default=0)),
                ('modify_count', models.PositiveIntegerField(default=0)),
                ('human_review_count', models.PositiveIntegerField(default=0)),
                ('was_blocked', models.BooleanField(default=False)),
                ('previous_decisions', models.JSONField(blank=True, default=list)),
                ('token_replacement_map', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('use_case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='session_states', to='core.usecaseprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PolicyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50)),
                ('thresholds', models.JSONField(blank=True, default=dict)),
                ('max_retries', models.PositiveSmallIntegerField(default=2)),
                ('latency_budget_ms', models.PositiveIntegerField(default=5000)),
                ('require_human_for_block', models.BooleanField(default=False)),
                ('session_risk_threshold', models.FloatField(default=5.0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('use_case_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_configs', to='core.usecaseprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='trace',
            index=models.Index(fields=['session_id'], name='core_trace_session_6aeb81_idx'),
        ),
        migrations.AddConstraint(
            model_name='policyconfig',
            constraint=models.UniqueConstraint(fields=('use_case_profile', 'version'), name='unique_policy_version_per_use_case'),
        ),
    ]
