# Generated by Django 6.1 on 2026-08-23 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionstate',
            name='recent_risk_scores',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
