# Generated by Django 6.1 on 2026-08-23 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sessionstate_recent_risk_scores'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThresholdChangeProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_case_id', models.CharField(max_length=100)),
                ('bucket', models.CharField(max_length=20)),
                ('dimension', models.CharField(max_length=50)),
                ('current_threshold', models.FloatField()),
                ('proposed_threshold', models.FloatField()),
                ('rationale', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('proposed_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.CharField(blank=True, max_length=200)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-proposed_at'],
            },
        ),
        migrations.AddField(
            model_name='auditrecord',
            name='human_review_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('DECIDED', 'Decided')], max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='FalsePositiveReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension', models.CharField(max_length=50)),
                ('reported_by', models.CharField(max_length=200)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audit_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='false_positive_reports', to='core.auditrecord')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewerAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_id', models.CharField(max_length=200)),
                ('decision', models.CharField(choices=[('APPROVE', 'Approve'), ('MODIFY', 'Modify'), ('REJECT', 'Reject')], max_length=10)),
                ('decision_reason', models.TextField(blank=True)),
                ('modified_response', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('audit_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_actions', to='core.auditrecord')),
            ],
            options={
                'ordering': ['-decided_at'],
            },
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True)),
                ('reviewed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_entries', to='core.trace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
