# Generated by Django 6.1 on 2026-08-23 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_thresholdchangeproposal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditrecord',
            name='compliance_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='usecaseprofile',
            name='eu_ai_act_high_risk',
            field=models.BooleanField(default=False),
        ),
    ]
