# Generated by Django 6.1 on 2026-08-30 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditrecord',
            name='prompt_audit',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditrecord',
            name='verify_warnings',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
