# Generated by Django 6.1 on 2026-08-30 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auditrecord_prompt_audit_auditrecord_verify_warnings'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='policyconfig',
            name='unique_policy_version_per_use_case',
        ),
        migrations.RemoveField(
            model_name='sessionstate',
            name='use_case',
        ),
        migrations.RemoveField(
            model_name='trace',
            name='use_case',
        ),
        migrations.DeleteModel(
            name='PolicyConfig',
        ),
        migrations.DeleteModel(
            name='UseCaseProfile',
        ),
    ]
