"""
Django settings for controlplane project.

Generated by 'django-admin startproject' using Django 5.1.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
import sys
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")

# True under `manage.py test`. core.model_pipeline reads this to avoid
# making live, quota-limited, non-deterministic third-party model calls
# from the automated test suite — the same reason DEBUG/SECRET_KEY etc.
# are environment-driven rather than hardcoded.
TESTING = "test" in sys.argv


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Read from the environment so the deployed key is never committed. The
# fallback below is for local development and `manage.py test` only.
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-local-development-only-never-use-in-production',
)

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to off, so a forgotten env var can never expose tracebacks on a
# public deployment. Local development sets DJANGO_DEBUG=True in .env.
DEBUG = os.environ.get('DJANGO_DEBUG', 'False').lower() == 'true'

# Railway injects RAILWAY_PUBLIC_DOMAIN with the service's public hostname,
# so the deployment needs no manual host configuration.
ALLOWED_HOSTS = [h.strip() for h in os.environ.get('DJANGO_ALLOWED_HOSTS', '').split(',') if h.strip()]
_public_domain = os.environ.get('RAILWAY_PUBLIC_DOMAIN')
if _public_domain:
    ALLOWED_HOSTS.append(_public_domain)
if not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1']

# Django requires the scheme here. Railway serves every deployment over
# HTTPS, so POSTs from the dashboards/playground need the origin trusted.
CSRF_TRUSTED_ORIGINS = [
    f'https://{h}' for h in ALLOWED_HOSTS if h not in ('localhost', '127.0.0.1')
]

# Railway terminates TLS at its edge and forwards the request over plain
# HTTP; without this Django believes the request was insecure.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Cookie/redirect hardening, applied only when DEBUG is off so local
# development over plain http keeps working. HSTS is deliberately left
# unset: it is browser-cached and hard to walk back, which is not a
# trade worth making on a temporary *.up.railway.app hostname.
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# Role-based access control (core/authz.py, core/auth_views.py): employees
# only reach Playground, managers reach every dashboard page. Any
# @login_required redirect (or the login view's own fallback) sends an
# unauthenticated visitor here.
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'playground'
LOGOUT_REDIRECT_URL = 'login'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'controlplane.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.access',
            ],
        },
    },
]

WSGI_APPLICATION = 'controlplane.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('DB_NAME', 'controlplane_db'),
        'USER': os.environ.get('DB_USER', 'root'),
        'PASSWORD': os.environ.get('DB_PASSWORD', ''),
        'HOST': os.environ.get('DB_HOST', '127.0.0.1'),
        'PORT': os.environ.get('DB_PORT', '3306'),
        'OPTIONS': {
            'charset': 'utf8mb4',
        },
    }
}

# Section 3 Step 9 MODIFY: "Logs the original content (encrypted) ... to
# the audit log for compliance review." Used by core/decision_executor.py.
MODIFICATION_LOG_ENCRYPTION_KEY = os.environ.get('MODIFICATION_LOG_ENCRYPTION_KEY')


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# `collectstatic` target. The app's own CSS is inlined in base.html, so this
# exists to serve django.contrib.admin's assets when DEBUG is False.
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage'},
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
